// Generated by CoffeeScript 1.3.3
(function() {
  var Person, obj;

  Person = (function() {

    function Person(name) {
      console.log("Hello");
    }

    Person.prototype.sayname = function() {
      return console.log("Hello Ted");
    };

    Person.prototype.what = function() {
      return console.log("what");
    };

    return Person;

  })();

  obj = new Person("Ted");

  obj.sayname;

  obj.what;

}).call(this);
